# Generated by Django 5.2.2 on 2025-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='bookings_bo_client__ca5b55_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_time'], name='bookings_bo_booking_238b42_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['fitness_class', 'booking_time'], name='bookings_bo_fitness_e1b4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['date_time'], name='bookings_fi_date_ti_98d1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['instructor'], name='bookings_fi_instruc_3ebb80_idx'),
        ),
    ]
